In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Notebook 01: SAMSum Dataset Exploration
Objective:
- Download SAMSum dataset
- Inspect structure and samples
- Understand dialogue–summary pairs
- Prepare for data ingestion pipeline

In [3]:
!pip install -r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt

Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 2)) (6.0.3)
Requirement already satisfied: python-box in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 3)) (7.3.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 4)) (4.67.1)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 7)) (2.9.0+cpu)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 8)) (4.57.6)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 9)) (4.0.0)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 10)) (0.2.1)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 11)) (1.12.0)
Collecting rouge-score (from -r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 14))
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting evaluate (from -r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 15))
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 18)) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 19)) (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 20)) (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 21)) (0.13.2)
Collecting streamlit (from -r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24))
  Downloading streamlit-1.53.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 27)) (1.6.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 7)) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 7)) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 7)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 7)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 7)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 7)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 7)) (2025.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 8)) (0.36.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 8)) (25.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 8)) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 8)) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 8)) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 8)) (0.7.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 9)) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 9)) (0.3.8)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 9)) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 9)) (0.70.16)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 11)) (5.9.5)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge-score->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 14)) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge-score->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 14)) (3.9.1)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge-score->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 14)) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 19)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 19)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 19)) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 20)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 20)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 20)) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 20)) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 20)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 20)) (3.3.2)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24)) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24)) (1.9.0)
Requirement already satisfied: cachetools<7,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24)) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24)) (8.3.1)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24)) (5.29.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24)) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24)) (0.10.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24)) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24)) (3.1.46)
Collecting pydeck<1,>=0.8.0b4 (from streamlit->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24))
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24)) (6.5.1)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 27)) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 27)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 27)) (3.6.0)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24)) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24)) (2.15.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 9)) (3.13.3)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24)) (4.0.12)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 8)) (1.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 7)) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 8)) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 8)) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 8)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 8)) (2026.1.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 7)) (1.3.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 9)) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 9)) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 9)) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 9)) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 9)) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 9)) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 9)) (1.22.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24)) (5.0.2)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24)) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24)) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/requirements.txt (line 24)) (0.30.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.1 MB/s eta 0:00:00
Downloading streamlit-1.53.1-py3-none-any.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 69.5 MB/s eta 0:00:00
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 95.5 MB/s eta 0:00:00
Building wheels for collected packages: rouge-score
  Building wheel for rouge-score (setup.py) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=2fb4d722c5c2f749108181f01f706ecb380ba22c8a5b288e1a3e11cc37c5f53e
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge-score
Installing collected packages: rouge-score, pydeck, streamlit, evaluate
Successfully installed evaluate-0.4.6 pydeck-0.9.1 rouge-score-0.1.2 streamlit-1.53.1

In [4]:
import sys
print("Python version:", sys.version)

Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]

In [5]:
from datasets import load_dataset
import pandas as pd

In [7]:
dataset = load_dataset("knkarthick/samsum")
dataset

README.md: 0.00B [00:00, ?B/s]

train.csv: 0.00B [00:00, ?B/s]

validation.csv: 0.00B [00:00, ?B/s]

test.csv: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/14731 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/818 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/819 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['id', 'dialogue', 'summary'],
        num_rows: 14731
    })
    validation: Dataset({
        features: ['id', 'dialogue', 'summary'],
        num_rows: 818
    })
    test: Dataset({
        features: ['id', 'dialogue', 'summary'],
        num_rows: 819
    })
})

In [10]:
for split in dataset:
    print(f"{split} size: {len(dataset[split])}")

train size: 14731
validation size: 818
test size: 819

In [11]:
dataset["train"][0]

{'id': '13818513',
 'dialogue': "Amanda: I baked  cookies. Do you want some?\nJerry: Sure!\nAmanda: I'll bring you tomorrow :-)",
 'summary': 'Amanda baked cookies and will bring Jerry some tomorrow.'}

In [12]:
train_df = pd.DataFrame(dataset["train"])
train_df.head()

,id,dialogue,summary
0,13818513,Amanda: I baked cookies. Do you want some?\nJ...,Amanda baked cookies and will bring Jerry some...
1,13728867,Olivia: Who are you voting for in this electio...,Olivia and Olivier are voting for liberals in ...
2,13681000,"Tim: Hi, what's up?\nKim: Bad mood tbh, I was ...",Kim may try the pomodoro technique recommended...
3,13730747,"Edward: Rachel, I think I'm in ove with Bella....",Edward thinks he is in love with Bella. Rachel...
4,13728094,Sam: hey overheard rick say something\nSam: i...,"Sam is confused, because he overheard Rick com..."

In [13]:
print("Dialogue:\n")
print(train_df.loc[0, "dialogue"])

print("\nSummary:\n")
print(train_df.loc[0, "summary"])

Dialogue:

Amanda: I baked  cookies. Do you want some?
Jerry: Sure!
Amanda: I'll bring you tomorrow :-)

Summary:

Amanda baked cookies and will bring Jerry some tomorrow.

In [14]:
train_df["dialogue_word_count"] = train_df["dialogue"].apply(lambda x: len(x.split()))
train_df["summary_word_count"] = train_df["summary"].apply(lambda x: len(x.split()))

train_df[["dialogue_word_count", "summary_word_count"]].describe()

       dialogue_word_count  summary_word_count
count         14731.000000        14731.000000
mean             93.792750           20.318444
std              74.031937           11.153570
min               7.000000            1.000000
25%              39.000000           12.000000
50%              73.000000           18.000000
75%             128.000000           27.000000
max             803.000000           64.000000

### Observations
- Dialogues are informal and multi-turn
- Summaries are concise and abstractive
- Large variance in dialogue length
- Confirms need for transformer-based summarization

In [15]:
from pathlib import Path

RAW_DATA_DIR = Path("/content/drive/MyDrive/ml_projects/NLP_Text_Summarization/artifacts/data/raw")
RAW_DATA_DIR.mkdir(parents=True, exist_ok=True)
RAW_DATA_DIR

PosixPath('/content/drive/MyDrive/ml_projects/NLP_Text_Summarization/artifacts/data/raw')

In [16]:
for split in dataset.keys():
    output_path = RAW_DATA_DIR / f"samsum_{split}.json"
    dataset[split].to_json(output_path)
    print(f"Saved {split} split to {output_path}")

Creating json from Arrow format:   0%|          | 0/15 [00:00<?, ?ba/s]

Saved train split to /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/artifacts/data/raw/samsum_train.json

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Saved validation split to /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/artifacts/data/raw/samsum_validation.json

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Saved test split to /content/drive/MyDrive/ml_projects/NLP_Text_Summarization/artifacts/data/raw/samsum_test.json

- Files in `artifacts/data/raw/` are immutable
- No preprocessing is applied at this stage
- All future pipelines must read from these files
- Dataset source: Hugging Face (knkarthick/samsum)